setup
blumilksoftware/gha-analyzer pull request #9
Opened 2024-06-05 08:20 UTC by orlowski11

Created initial setup for the application

2024-06-05 11:06 UTC, JakubKermes commented
Maybe we could start with Laravel 11?

2024-06-05 11:22 UTC, kamilpiech97 requested changes

2024-06-05 11:22 UTC, kamilpiech97 commented on .env.example
> +VITE_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
Pusher will be used in app?

2024-06-05 11:22 UTC, kamilpiech97 commented on database/seeders/DatabaseSeeder.php
> +     */
Lets use [Blumilk codestyle](https://github.com/blumilksoftware/codestyle) for some cleaning in project

2024-06-05 11:22 UTC, kamilpiech97 commented on database/seeders/DatabaseSeeder.php
> +        // ]);
Is it need?

2024-06-05 11:22 UTC, kamilpiech97 commented on docker-compose.yml
> +                WWWGROUP: '${WWWGROUP}'
Are u ok with sail?
Maybe lets use our [boilerplate](https://github.com/blumilksoftware/boilerplate).

2024-06-05 11:22 UTC, kamilpiech97 commented on composer.json
> +        "laravel/pint": "^1.0",
Lest use Blumilk codestyle - https://github.com/blumilksoftware/codestyle

2024-06-05 11:22 UTC, kamilpiech97 commented on docker-compose.yml
> +    laravel.test:
The naming of services and other things seems to refer to the project name

2024-06-05 11:22 UTC, kamilpiech97 commented on app/Http/Requests/Auth/LoginRequest.php
> +     */
Should be cleared

2024-06-05 11:23 UTC, kamilpiech97 commented
> Maybe we could start with Laravel 11?

Yep, I think that should be obligatory.

2024-06-07 06:36 UTC, JakubKermes approved these changes

2024-06-10 06:40 UTC, krzysztofrewak approved these changes

2024-06-10 07:16 UTC, kamilpiech97 approved these changes

2024-06-10 07:18 UTC, merged